[server]
maxUploadSize = 10
maxMessageSize = 10

[browser]
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#17408B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
